uploads = []
generated = []

[[outputs]]
id = "0ySybj2JtYkdhKU4pVHSf"
uri = "file://tibbhouse-core.zip"
type = "unspecified"
title = "Tibb House Core – WordPress Plugin (updated template loader)"

[[outputs]]
id = "EciiWgNOjRQY4JZVhFpSr"
uri = "file://tibbhouse-core-v2.zip"
type = "unspecified"
title = "tibbhouse-core-v2.zip — WordPress Plugin"

[[outputs]]
id = "_f16TAM35PywXFyysvOSW"
uri = "file://tibbhouse-core-v3.zip"
type = "unspecified"
title = "Tibb House Core – WordPress Plugin (v3, Astra template override fix)"

[[outputs]]
id = "9PSzIJhGkvK1HbAwayODw"
uri = "file://tibbhouse-complete.zip"
type = "unspecified"
title = "tibbhouse-complete.zip — Plugin + Theme"
