uploads = []
generated = []

[[outputs]]
id = "0ySybj2JtYkdhKU4pVHSf"
uri = "file://tibbhouse-core.zip"
type = "unspecified"
title = "tibbhouse-core.zip — Upload via Plugins › Add New"

[[outputs]]
id = "EciiWgNOjRQY4JZVhFpSr"
uri = "file://tibbhouse-core-v2.zip"
type = "unspecified"
title = "tibbhouse-core-v2.zip — WordPress Plugin"

[[outputs]]
id = "_f16TAM35PywXFyysvOSW"
uri = "file://tibbhouse-core-v3.zip"
type = "unspecified"
title = "Tibb House Core – WordPress Plugin (v3, Astra template override fix)"

[[outputs]]
id = "9PSzIJhGkvK1HbAwayODw"
uri = "file://tibbhouse-complete.zip"
type = "unspecified"
title = "tibbhouse-complete.zip — Plugin + Theme (with Gallery & Video)"

[[outputs]]
id = "uBz4ZqFB0heiygc7kwAHQ"
uri = "file://tibbhouse-core-latest.zip"
type = "unspecified"
title = "Tibb House Core Plugin (updated)"

[[outputs]]
id = "3bDtMMyx21AgDeogzqlqN"
uri = "file://tibbhouse-theme-latest.zip"
type = "unspecified"
title = "Tibb House Theme (updated)"

[[outputs]]
id = "mhUfGwU0keUtW_aJYtbqy"
uri = "file://tibbhouse-theme.zip"
type = "unspecified"
title = "tibbhouse-theme.zip — Upload via Appearance › Themes"
