kind = "web"
previewPath = "/"
title = "Tibb House"
version = "1.0.0"
id = "artifacts/api-server"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22729

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/api-server", "run", "build" ]
serve = "static"
publicDir = "artifacts/api-server/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22729"
BASE_PATH = "/"
