kind = "web"
previewPath = "/"
title = "Tibb House"
version = "1.0.0"
id = "artifacts/api-server"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22729

[services.development]
run = "php -S 0.0.0.0:$PORT -t /home/runner/workspace/wordpress /home/runner/workspace/wordpress/router.php"

[services.env]
PORT = "22729"
BASE_PATH = "/"
